module.exports = ->
  service = getJsonFromFile: getJsonFromFile

  getJsonFromFile = (file) ->
    fs = require('fs')
    json = getConfig(file)

    readJsonFileSync = (filepath, encoding) ->
      `var file`
      if typeof encoding == 'undefined'
        encoding = 'utf8'
      file = fs.readFileSync(filepath, encoding)
      JSON.parse file

    getConfig = (file) ->
      filepath = __dirname + file
      readJsonFileSync filepath

    json

  service

# ---
# generated by js2coffee 2.1.0